# Generated by Django 3.2.5 on 2021-07-12 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210712_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='has_size',
            new_name='has_sizes',
        ),
    ]
